name: 'Terraform Down'

on:
  schedule:
    - cron: "0 21 * * 1-5"

jobs:
  terraform:
    name: 'Terraform Down'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform 
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    
    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt 
    
    - name: Terraform Destroy
      run: terraform destroy -auto-approve -input=false
