name: 'Terraform Up'

on:
  schedule:
    - cron: "30 16 * * 1-5"
    # - cron: "30 11 * * 1-5"

jobs:
  terraform:
    name: 'Terraform Up'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform 
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init 

    - name: Terraform Format
      run: terraform fmt
    
    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
  